github_owner=zephyr7030
github_repo=DroidBridge
manifest_url=https://github.com/zephyr7030/DroidBridge/releases/latest/download/release.json
apk_signer_sha256=f4220a0f1672a43ec8dab46102ba9c9600116f2ef1bb94033b1f64dee8126e68
release_key_id=p256-a83fc3a3c8443c71
release_public_key_base64=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzdraKsSuejSX/jtbIjJT8wUpA2WAIduPpSFDS34BybOPEWc0bhZIzgeAFG033v31nkQteEuRINEYDuDcU6e0Tg==
