[package]
name = "contract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true

[[bin]]
name = "generate-contract"
path = "src/bin/generate_contract.rs"
